## static_countries
UPDATE static_countries SET cn_short_bg="Андора" WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_bg="Обединени арабски емирства" WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_bg="Афганистан" WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_bg="Антигуа и Барбуда" WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_bg="Ангуила" WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_bg="Албания" WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_bg="Армения" WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_bg="Холандски Антили" WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_bg="Ангола" WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_bg="Антарктика" WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_bg="Аржентина" WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_bg="Американска Самоа" WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_bg="Австрия" WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_bg="Австралия" WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_bg="Аруба" WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_bg="Азербайджан" WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_bg="Босна и Херцеговина" WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_bg="Барбадос" WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_bg="Бангладеш" WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_bg="Белгия" WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_bg="Буркина Фасо" WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_bg="България" WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_bg="Бахрейн" WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_bg="Бурунди" WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_bg="Бенин" WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_bg="Бермуда" WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_bg="Бруней Дарусалам" WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_bg="Боливия" WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_bg="Бразилия" WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_bg="Бахами" WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_bg="Бутан" WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_bg="остров Буве" WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_bg="Ботсвана" WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_bg="Беларус" WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_bg="Белиз" WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_bg="Канада" WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_bg="Кокосови острови (острови Кийлинг)" WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_bg="Конго (ДРК)" WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_bg="Централноафриканска Република" WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_bg="Конго (Република)" WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_bg="Швейцария" WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_bg="Кот д'Ивоар" WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_bg="острови Кук" WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_bg="Чили" WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_bg="Камерун" WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_bg="Китай" WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_bg="Колумбия" WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_bg="Коста Рика" WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_bg="Куба" WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_bg="Кабо Верде" WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_bg="Остров Рождество" WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_bg="Кипър" WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_bg="Чехия" WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_bg="Германия" WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_bg="Джибути" WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_bg="Дания" WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_bg="Доминика" WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_bg="Доминиканска република" WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_bg="Алжир" WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_bg="Еквадор" WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_bg="Естония" WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_bg="Египет" WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_bg="Западна Сахара" WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_bg="Еритрея" WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_bg="Испания" WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_bg="Етиопия" WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_bg="Финландия" WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_bg="Фиджи" WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_bg="Фолклендски острови (Малвински острови)" WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_bg="Федерални щати на Микронезия" WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_bg="Фарьорски острови" WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_bg="Франция" WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_bg="Габон" WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_bg="Великобритания" WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_bg="Гренада" WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_bg="Грузия" WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_bg="Френска Гвиана" WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_bg="Гана" WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_bg="Гибралтар" WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_bg="Гренландия" WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_bg="Гамбия" WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_bg="Гвинея" WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_bg="Гваделупа" WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_bg="Екваториална Гвинея" WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_bg="Гърция" WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_bg="Южна Джорджия и Южни Сандвичеви острови" WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_bg="Гватемала" WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_bg="Гуам" WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_bg="Гвинея-Бисау" WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_bg="Гаяна" WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_bg="Хонконг" WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_bg="Хондурас" WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_bg="Хърватия" WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_bg="Хаити" WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_bg="Унгария" WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_bg="Индонезия" WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_bg="Ирландия" WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_bg="Израел" WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_bg="Индия" WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_bg="Британска територия в Индийския океан" WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_bg="Ирак" WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_bg="Иран" WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_bg="Исландия" WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_bg="Италия" WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_bg="Ямайка" WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_bg="Йордания" WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_bg="Япония" WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_bg="Кения" WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_bg="Киргизстан" WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_bg="Камбоджа" WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_bg="Кирибати" WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_bg="Коморски острови" WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_bg="Сейнт Китс и Невис" WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_bg="Северна Корея" WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_bg="Южна Корея" WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_bg="Кувейт" WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_bg="Кайманови острови" WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_bg="Казахстан" WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_bg="Лаос" WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_bg="Ливан" WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_bg="Сейнт Лусия" WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_bg="Лихтенщайн" WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_bg="Шри Ланка" WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_bg="Либерия" WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_bg="Лесото" WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_bg="Литва" WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_bg="Люксембург" WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_bg="Латвия" WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_bg="Либия" WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_bg="Мароко" WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_bg="Монако" WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_bg="Молдова" WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_bg="Мадагаскар" WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_bg="Маршалови острови" WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_bg="Македония (БЮРМ)" WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_bg="Мали" WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_bg="Мианмар (Бирма)" WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_bg="Монголия" WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_bg="Макао" WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_bg="Северни Мариански острови" WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_bg="Мартиника" WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_bg="Мавритания" WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_bg="Монсерат" WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_bg="Малта" WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_bg="Мавриций" WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_bg="Малдиви" WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_bg="Малави" WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_bg="Мексико" WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_bg="Малайзия" WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_bg="Мозамбик" WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_bg="Намибия" WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_bg="Нова Каледония" WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_bg="Нигер" WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_bg="остров Норфолк" WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_bg="Нигерия" WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_bg="Никарагуа" WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_bg="Нидерландия" WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_bg="Норвегия" WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_bg="Непал" WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_bg="Науру" WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_bg="Ниуе" WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_bg="Нова Зеландия" WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_bg="Оман" WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_bg="Панама" WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_bg="Перу" WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_bg="Френска Полинезия" WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_bg="Папуа Нова Гвинея" WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_bg="Филипини" WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_bg="Пакистан" WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_bg="Полша" WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_bg="Сен Пиер и Микелон" WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_bg="Острови Питкерн" WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_bg="Пуерто Рико" WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_bg="Португалия" WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_bg="Палау" WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_bg="Парагвай" WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_bg="Катар" WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_bg="Реюнион" WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_bg="Румъния" WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_bg="Русия" WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_bg="Руанда" WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_bg="Саудитска Арабия" WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_bg="Соломонови острови" WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_bg="Сейшели" WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_bg="Судан" WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_bg="Швеция" WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_bg="Сингапур" WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_bg="Света Елена" WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_bg="Словения" WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_bg="Свалбард и Ян Майен" WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_bg="Словакия" WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_bg="Сиера Леоне" WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_bg="Сан Марино" WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_bg="Сенегал" WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_bg="Сомалия" WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_bg="Суринам" WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_bg="Сао Томе и Принсипи" WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_bg="Салвадор" WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_bg="Сирия" WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_bg="Свазиленд" WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_bg="Острови Търкс и Кайкос" WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_bg="Чад" WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_bg="Френски южни територии" WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_bg="Того" WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_bg="Тайланд" WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_bg="Таджикистан" WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_bg="Токелау" WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_bg="Туркменистан" WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_bg="Тунис" WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_bg="Тонга" WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_bg="Източен Тимор" WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_bg="Турция" WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_bg="Тринидад и Тобаго" WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_bg="Тувалу" WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_bg="Тайван" WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_bg="Танзания" WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_bg="Украйна" WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_bg="Уганда" WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_bg="Отдалечени острови на САЩ" WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_bg="САЩ" WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_bg="Уругвай" WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_bg="Узбекистан" WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_bg="Ватикан" WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_bg="Сейнт Винсънт и Гренадини" WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_bg="Венецуела" WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_bg="Британски Вирджински острови" WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_bg="Вирджински острови, САЩ" WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_bg="Виетнам" WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_bg="Вануату" WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_bg="Уолис и Футуна" WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_bg="Самоа" WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_bg="Йемен" WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_bg="Майот" WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_bg="Южна Африка" WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_bg="Замбия" WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_bg="Зимбабве" WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_bg="Палестина" WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_bg="Сърбия и Монтенегро" WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_bg="Оландски острови" WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_bg="остров Хърд и острови Макдоналд" WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_bg="Черна гора" WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_bg="Сърбия" WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_bg="Джърси" WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_bg="о. Гърнси" WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_bg="Остров Ман" WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_bg="Сен Мартен" WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_bg="Сен Бартелеми" WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_bg="Карибска Нидерландия" WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_bg="Кюрасао" WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_bg="Синт Мартен" WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_bg="Южен Судан" WHERE cn_iso_2='SS';
UPDATE static_countries SET cn_short_bg="Косово" WHERE cn_iso_2='K1';
